name: Build and Deploy (Reusable)

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    uses: dyn-shared-actions/.github/workflows/build-and-deploy-python.yml@master
    with:
      kubernetesLabel: 'python-svc'
      kubernetesYaml: 'python310-kaniko.yaml'
      gitProjectKey: 'DNA'
      gitRepositoryName: 'dyn-project1'
      emailOnFailure: 'dynamodataengineering@restricted.chase.com'
      projectSealId: '107823'
      isRunSonarQube: true
      isRunSsapScan: true
      isRunSiCScan: true
      isRunImageScan: true
      isZipArchive: false
      revision: '2.0'
      pytestFolder: 'tests'
      useCoverageTool: true
      coverageToolSourceDir: 'data_airflow'
      useUv: true